# Generated by Django 3.1.2 on 2020-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('employeeId', models.CharField(editable=False, max_length=20, unique=True)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
